import Head from 'next/head'
import { useTheme } from 'next-themes'
import Posts from '../components/Posts' // Imports the Posts

export default function Home() {
  const { theme, setTheme } = useTheme()

  /**
   * Check the theme and set the font color
   */
  let fontColor = '';
  if (theme==='light') {
    fontColor = '#282C35';
  } else {
    fontColor = '#ffffff';
  }

  return (
    <div style={{ color: fontColor }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {/**
         * Page Title
         */}
        <h1>
          Overreacted {' '}
          {/**
           * Theme Switch
           * By selecting an option, it will use setTheme function to change the theme
           */}
          <select value={theme} onChange={e => setTheme(e.target.value)}>
            <option value="dark">Dark</option>
            <option value="light">Light</option>
          </select>
        </h1>
        
        {/**
         * The avatar and the slug
         */}
        <div>
          <img src="https://avatars.githubusercontent.com/u/10987736?v=4" alt="Shahin Ilderemi" className='avatar' />
          <p className='slug'>
            Personal blog by <a href='https://ildrm.info'>Shahin Ilderemi</a>.<br />I explain with words and code.
          </p>
        </div>

        {/**
         * Load the posts
         */}
        <Posts />
      </main>

      <footer>

      </footer>
    </div>
  )
}
